# -*- coding: utf-8 -*-
"""Proyecto_Clasificador_Diabetes_Corregido.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-JIDQn-jnPsdcx_ol_jtmMciHyIZc71O

# Proyecto ML — Clasificador de Diabetes
**Redes Neuronales con PyTorch | Modelos A–J del PDF**

Bloque 0 — EDA
"""

# ── EDA — Análisis Exploratorio ───────────────────────────────────────────
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from google.colab import drive
drive.mount('/content/drive')


df = pd.read_excel('/content/drive/MyDrive/Proyecto_Diabetes/diab.xlsx')

# Estadísticas descriptivas
print("── Estadísticas descriptivas ──")
display(df.describe().round(2))

# Distribución de cada característica
fig, axes = plt.subplots(3, 3, figsize=(14, 10))
axes = axes.flatten()
cols = df.columns.tolist()

for i, col in enumerate(cols):
    axes[i].hist(df[col], bins=25, color='steelblue', edgecolor='white', alpha=0.8)
    axes[i].set_title(col)
    axes[i].set_xlabel('Valor')
    axes[i].set_ylabel('Frecuencia')
    axes[i].grid(True, alpha=0.3)

plt.suptitle('Distribución de Características', fontsize=14)
plt.tight_layout()
plt.show()

# Matriz de correlación
plt.figure(figsize=(10, 7))
sns.heatmap(df.corr(), annot=True, fmt='.2f', cmap='coolwarm',
            square=True, linewidths=0.5)
plt.title('Matriz de Correlación')
plt.tight_layout()
plt.show()

# Correlación con la variable objetivo
corr_target = df.corr()['Diagnose'].drop('Diagnose').sort_values(ascending=False)
plt.figure(figsize=(8, 4))
corr_target.plot(kind='bar', color='steelblue', edgecolor='white')
plt.axhline(0, color='black', linewidth=0.8)
plt.title('Correlación de cada característica con Diagnose')
plt.ylabel('Coeficiente de Pearson')
plt.xticks(rotation=30)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

print("\nVariables más correlacionadas con el diagnóstico:")
print(corr_target)

"""## Bloque 1 — Preparación de Datos"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')

# ── Carga del dataset ──────────────────────────────────────────────────────
df = pd.read_excel('/content/drive/MyDrive/Proyecto_Diabetes/diab.xlsx')
print('Forma del dataset:', df.shape)
print('\nTipos de columnas:\n', df.dtypes)
display(df.head())

# ── Análisis de desbalance de clases ──────────────────────────────────────
conteos = df['Diagnose'].value_counts()

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Diagnose', palette='viridis')
plt.title('Distribución de Clases: 0 (No Diabético) vs 1 (Diabético)')
plt.ylabel('Número de Pacientes')
plt.show()

print(f"\nClase 0 (No Diabéticos): {conteos[0]} pacientes ({conteos[0]/len(df)*100:.1f}%)")
print(f"Clase 1 (Diabéticos):    {conteos[1]} pacientes ({conteos[1]/len(df)*100:.1f}%)")
print("\nHay desbalance de clases. Esto puede inflar el Accuracy e ignorar")
print("los errores en la clase minoritaria, por eso también usamos F1 y AUC.")

# ── Separar features y target ─────────────────────────────────────────────
X = df.drop('Diagnose', axis=1).values
y = df['Diagnose'].values

# ── Partición 70 / 15 / 15 con estratificación ────────────────────────────
# stratify=y asegura la misma proporción de clases en los 3 subconjuntos
X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42, stratify=y
)
X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp, test_size=0.1765, random_state=42, stratify=y_temp
)

print(f"\nEntrenamiento: {X_train.shape[0]} muestras")
print(f"Validación:    {X_val.shape[0]} muestras")
print(f"Prueba:        {X_test.shape[0]} muestras")

# ── Normalización (Z-Score) ───────────────────────────────────────────────
# El scaler aprende media y std SOLO del set de entrenamiento.
# Luego aplica esa misma transformación a val y test para no contaminarlos.
scaler = StandardScaler()
X_train_norm = scaler.fit_transform(X_train)
X_val_norm   = scaler.transform(X_val)
X_test_norm  = scaler.transform(X_test)

# ── Conversión a tensores de PyTorch ──────────────────────────────────────
def a_tensores(X_np, y_np):
    X_t = torch.tensor(X_np, dtype=torch.float32)
    y_t = torch.tensor(y_np, dtype=torch.float32).view(-1, 1)
    return X_t, y_t

# Versiones normalizadas
X_train_norm_t, y_train_t = a_tensores(X_train_norm, y_train)
X_val_norm_t,   y_val_t   = a_tensores(X_val_norm,   y_val)
X_test_norm_t,  y_test_t  = a_tensores(X_test_norm,  y_test)

# Versiones sin normalizar (para el escenario A–D del PDF)
X_train_raw_t, _ = a_tensores(X_train, y_train)
X_val_raw_t,   _ = a_tensores(X_val,   y_val)
X_test_raw_t,  _ = a_tensores(X_test,  y_test)

# ── DataLoaders ───────────────────────────────────────────────────────────
# El PDF pide explorar batch sizes: 4, 8, 16, 32, 64.
# Usamos 32 para los experimentos principales.
BATCH_SIZE = 32

def crear_loaders(X_t, y_t, X_v, y_v, batch_size=32):
    train_ds = TensorDataset(X_t, y_t)
    val_ds   = TensorDataset(X_v, y_v)
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_loader   = DataLoader(val_ds,   batch_size=batch_size, shuffle=False)
    return train_loader, val_loader

train_loader_norm, val_loader_norm = crear_loaders(
    X_train_norm_t, y_train_t, X_val_norm_t, y_val_t, BATCH_SIZE
)
train_loader_raw, val_loader_raw = crear_loaders(
    X_train_raw_t, y_train_t, X_val_raw_t, y_val_t, BATCH_SIZE
)

print(f"\nDataLoaders listos | Batch size={BATCH_SIZE}")
print(f"Batches por época (train norm): {len(train_loader_norm)}")

"""## Bloque 2 — Arquitectura y Motor de Entrenamiento"""

import torch.nn as nn
import torch.optim as optim
import copy
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, roc_auc_score, roc_curve
)

# ── Arquitectura dinámica ─────────────────────────────────────────────────
# neuronas_lista es una LISTA con el número de neuronas de cada capa oculta.
# Ejemplo: [64, 32] crea dos capas ocultas de 64 y 32 neuronas respectivamente.
# clase_activacion es la CLASE (no instancia) para crear una copia nueva por capa.
class RedDiabetes(nn.Module):
    def __init__(self, num_features, neuronas_lista, clase_activacion):
        super(RedDiabetes, self).__init__()

        capas = []
        entrada = num_features

        for neuronas in neuronas_lista:
            capas.append(nn.Linear(entrada, neuronas))
            capas.append(clase_activacion())  # nueva instancia por capa
            entrada = neuronas

        # Capa de salida: 1 neurona (clasificación binaria)
        # BCEWithLogitsLoss espera logits, NO probabilidades, así que NO se aplica Sigmoid aquí
        capas.append(nn.Linear(entrada, 1))

        self.red = nn.Sequential(*capas)

    def forward(self, x):
        return self.red(x)


# ── Función de entrenamiento con mini-batches y early stopping ────────────
def entrenar_modelo(config, train_loader, val_loader, num_features,
                    epocas=500, paciencia=20):
    """
    Entrena la red y devuelve:
      - El modelo con los MEJORES pesos (según val loss)
      - Historial de pérdida de entrenamiento y validación
      - Mejor val loss alcanzado
      - Época en que se detuvo
    """
    modelo = RedDiabetes(
        num_features=num_features,
        neuronas_lista=config['neuronas'],
        clase_activacion=config['act']
    )

    # BCEWithLogitsLoss = Sigmoid + BCELoss combinadas; más estable numéricamente
    criterio = nn.BCEWithLogitsLoss()

    # weight_decay implementa la regularización L2 (penaliza pesos grandes)
    optimizador = optim.Adam(
        modelo.parameters(), lr=config['lr'], weight_decay=config['l2']
    )

    hist_train, hist_val = [], []
    mejor_val_loss = float('inf')
    contador_paciencia = 0
    mejor_pesos = None
    epoca_parada = epocas

    for ep in range(epocas):
        # -- ENTRENAMIENTO (mini-batches) --
        modelo.train()
        loss_train_acum = 0.0
        for X_batch, y_batch in train_loader:
            optimizador.zero_grad()
            salida = modelo(X_batch)
            loss   = criterio(salida, y_batch)
            loss.backward()
            optimizador.step()
            loss_train_acum += loss.item() * X_batch.size(0)

        loss_train_ep = loss_train_acum / len(train_loader.dataset)

        # -- VALIDACIÓN --
        modelo.eval()
        loss_val_acum = 0.0
        with torch.no_grad():
            for X_batch, y_batch in val_loader:
                salida = modelo(X_batch)
                loss   = criterio(salida, y_batch)
                loss_val_acum += loss.item() * X_batch.size(0)

        loss_val_ep = loss_val_acum / len(val_loader.dataset)

        hist_train.append(loss_train_ep)
        hist_val.append(loss_val_ep)

        # -- EARLY STOPPING --
        if loss_val_ep < mejor_val_loss:
            mejor_val_loss = loss_val_ep
            contador_paciencia = 0
            # deepcopy para guardar una copia real de los pesos, no una referencia
            mejor_pesos = copy.deepcopy(modelo.state_dict())
        else:
            contador_paciencia += 1

        if contador_paciencia >= paciencia:
            epoca_parada = ep + 1
            break

    # Cargamos los mejores pesos (no los últimos, que pueden tener sobreajuste)
    modelo.load_state_dict(mejor_pesos)
    return modelo, hist_train, hist_val, mejor_val_loss, epoca_parada


# ── Función de evaluación completa ────────────────────────────────────────
def evaluar_modelo(modelo, X_test_t, y_test_t):
    """Devuelve todas las métricas del PDF para un modelo dado."""
    modelo.eval()
    with torch.no_grad():
        logits = modelo(X_test_t)
        # Sigmoid para convertir logits → probabilidades [0, 1]
        probs = torch.sigmoid(logits).numpy()

    preds = (probs >= 0.5).astype(int)
    y_np  = y_test_t.numpy()

    tn, fp, fn, tp = confusion_matrix(y_np, preds).ravel()

    acc  = accuracy_score(y_np, preds)
    prec = precision_score(y_np, preds, zero_division=0)
    rec  = recall_score(y_np, preds, zero_division=0)   # = Sensibilidad
    f1   = f1_score(y_np, preds, zero_division=0)
    esp  = tn / (tn + fp) if (tn + fp) > 0 else 0       # Especificidad manual
    auc  = roc_auc_score(y_np, probs)
    fpr, tpr, _ = roc_curve(y_np, probs)
    cm   = np.array([[tn, fp], [fn, tp]])

    return {
        'acc': acc, 'prec': prec, 'rec': rec, 'f1': f1,
        'esp': esp, 'auc': auc, 'fpr': fpr, 'tpr': tpr, 'cm': cm
    }

print('Arquitectura RedDiabetes y funciones de entrenamiento/evaluación listas.')

"""## Bloque 3 — Entrenamiento de los 10 Modelos (A–J del PDF)"""

import time

NUM_FEATURES = X_train_norm_t.shape[1]

# ── Configuraciones exactas del PDF (tabla de la página 3) ───────────────
# 'neuronas' es una lista: cada elemento = neuronas de esa capa oculta
# 'act' es la CLASE de activación (sin paréntesis) para instanciar una copia por capa
configuraciones = {
    # --- Sin normalización ---
    'A': {'norm': False, 'neuronas': [16],           'act': nn.ReLU,      'lr': 0.01,    'l2': 0.0},
    'B': {'norm': False, 'neuronas': [32, 16],        'act': nn.ReLU,      'lr': 0.001,   'l2': 0.0},
    'C': {'norm': False, 'neuronas': [64, 32],        'act': nn.Tanh,      'lr': 0.001,   'l2': 0.0},
    'D': {'norm': False, 'neuronas': [128, 64, 32],   'act': nn.ReLU,      'lr': 0.0001,  'l2': 0.0},
    # --- Con normalización ---
    'E': {'norm': True,  'neuronas': [16],            'act': nn.ReLU,      'lr': 0.01,    'l2': 0.0},
    'F': {'norm': True,  'neuronas': [32, 16],        'act': nn.ReLU,      'lr': 0.001,   'l2': 0.0},
    'G': {'norm': True,  'neuronas': [64, 32],        'act': nn.LeakyReLU, 'lr': 0.001,   'l2': 0.0},
    'H': {'norm': True,  'neuronas': [128, 64, 32],   'act': nn.ELU,       'lr': 0.0001,  'l2': 0.0},
    'I': {'norm': True,  'neuronas': [64, 32, 16, 8], 'act': nn.ReLU,      'lr': 0.0005,  'l2': 0.0},
    'J': {'norm': True,  'neuronas': [32],            'act': nn.Tanh,      'lr': 0.01,    'l2': 0.0},
}

resultados = {}
t0 = time.time()

print('Iniciando entrenamiento de los 10 modelos...\n')

for nombre, config in configuraciones.items():
    print(f'Entrenando Modelo {nombre}  '
          f'(norm={config["norm"]}, capas={len(config["neuronas"])}, '
          f'neuronas={config["neuronas"]}, lr={config["lr"]})...')

    # Elegir loaders y tensor de prueba según escenario
    if config['norm']:
        tl, vl    = train_loader_norm, val_loader_norm
        X_test_ev = X_test_norm_t
    else:
        tl, vl    = train_loader_raw, val_loader_raw
        X_test_ev = X_test_raw_t

    modelo, h_train, h_val, mejor_val, ep_parada = entrenar_modelo(
        config=config,
        train_loader=tl,
        val_loader=vl,
        num_features=NUM_FEATURES,
        epocas=500,
        paciencia=20
    )

    metricas = evaluar_modelo(modelo, X_test_ev, y_test_t)

    resultados[nombre] = {
        'modelo':     modelo,
        'hist_train': h_train,
        'hist_val':   h_val,
        'mejor_val':  mejor_val,
        'epocas':     ep_parada,
        'metricas':   metricas,
        'config':     config
    }
    print(f'  -> Paró en época {ep_parada} | Val Loss: {mejor_val:.4f} | '
          f'Acc: {metricas["acc"]:.4f} | AUC: {metricas["auc"]:.4f}\n')

print(f'Entrenamiento completado en {time.time()-t0:.1f} segundos.')

"""BLOQUE 3B"""

# ── Entrenar los mismos 10 modelos pero CON regularización L2 ─────────────
# Usamos L2 = 1e-4 para todos para tener una comparativa justa y controlada.
L2_VALOR = 1e-4

configuraciones_l2 = {
    nombre: {**cfg, 'l2': L2_VALOR}
    for nombre, cfg in configuraciones.items()
}

resultados_l2 = {}
t0 = time.time()
print(f'Entrenando 10 modelos CON L2 = {L2_VALOR}...\n')

for nombre, config in configuraciones_l2.items():
    print(f'Entrenando Modelo {nombre}_L2...')

    if config['norm']:
        tl, vl    = train_loader_norm, val_loader_norm
        X_test_ev = X_test_norm_t
    else:
        tl, vl    = train_loader_raw, val_loader_raw
        X_test_ev = X_test_raw_t

    modelo, h_train, h_val, mejor_val, ep_parada = entrenar_modelo(
        config=config,
        train_loader=tl,
        val_loader=vl,
        num_features=NUM_FEATURES,
        epocas=500,
        paciencia=20
    )

    metricas = evaluar_modelo(modelo, X_test_ev, y_test_t)

    resultados_l2[nombre] = {
        'modelo':     modelo,
        'hist_train': h_train,
        'hist_val':   h_val,
        'mejor_val':  mejor_val,
        'epocas':     ep_parada,
        'metricas':   metricas,
        'config':     config
    }
    print(f'  -> Época {ep_parada} | Val Loss: {mejor_val:.4f} | '
          f'Acc: {metricas["acc"]:.4f} | AUC: {metricas["auc"]:.4f}\n')

print(f'Listo en {time.time()-t0:.1f} segundos.')

"""## Bloque 4 — Visualizaciones y Tabla de Métricas"""

# ── 4.1 Curvas de Aprendizaje (10 gráficas) ───────────────────────────────
fig, axes = plt.subplots(5, 2, figsize=(14, 22))
axes = axes.flatten()

for i, (nombre, datos) in enumerate(resultados.items()):
    ax = axes[i]
    ax.plot(datos['hist_train'], label='Entrenamiento', color='steelblue', linewidth=1.5)
    ax.plot(datos['hist_val'],   label='Validación',    color='tomato',    linewidth=1.5)
    n_str = 'Con Norm' if datos['config']['norm'] else 'Sin Norm'
    ax.set_title(f'Modelo {nombre} — {n_str}\n'
                 f'Neuronas={datos["config"]["neuronas"]} | '
                 f'LR={datos["config"]["lr"]} | '
                 f'Épocas={datos["epocas"]}')
    ax.set_xlabel('Épocas')
    ax.set_ylabel('Pérdida (BCE)')
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.suptitle('Curvas de Aprendizaje — 10 Modelos', fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

# ── 4.2 Matrices de Confusión (heatmaps con seaborn) ─────────────────────
fig, axes = plt.subplots(5, 2, figsize=(12, 22))
axes = axes.flatten()

for i, (nombre, datos) in enumerate(resultados.items()):
    cm = datos['metricas']['cm']
    # Calcular porcentajes para anotar en la matriz
    cm_pct = cm.astype(float) / cm.sum() * 100
    labels = np.array([[f'{v}\n({p:.1f}%)' for v, p in zip(row_v, row_p)]
                        for row_v, row_p in zip(cm, cm_pct)])

    sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', ax=axes[i],
                xticklabels=['No Diab (0)', 'Diab (1)'],
                yticklabels=['No Diab (0)', 'Diab (1)'],
                linewidths=0.5)
    axes[i].set_title(f'Modelo {nombre} | Acc={datos["metricas"]["acc"]:.3f}')
    axes[i].set_xlabel('Predicción')
    axes[i].set_ylabel('Valor Real')

plt.suptitle('Matrices de Confusión — 10 Modelos', fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

# ── 4.3 Curvas ROC individuales + combinada ───────────────────────────────
fig, axes = plt.subplots(5, 2, figsize=(14, 22))
axes = axes.flatten()

for i, (nombre, datos) in enumerate(resultados.items()):
    m = datos['metricas']
    axes[i].plot(m['fpr'], m['tpr'], color='darkorange', lw=2,
                 label=f'AUC = {m["auc"]:.3f}')
    axes[i].plot([0, 1], [0, 1], 'k--', lw=1)
    axes[i].set_xlabel('FPR (1 - Especificidad)')
    axes[i].set_ylabel('TPR (Sensibilidad)')
    axes[i].set_title(f'ROC — Modelo {nombre}')
    axes[i].legend(loc='lower right')
    axes[i].grid(True, alpha=0.3)

plt.suptitle('Curvas ROC — Modelos A al J', fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

# Curva ROC combinada
plt.figure(figsize=(10, 7))
colores = plt.cm.tab10(np.linspace(0, 1, 10))
for (nombre, datos), color in zip(resultados.items(), colores):
    m = datos['metricas']
    plt.plot(m['fpr'], m['tpr'], color=color,
             label=f'Modelo {nombre} (AUC={m["auc"]:.3f})')
plt.plot([0, 1], [0, 1], 'k--', label='Clasificador Aleatorio')
plt.xlabel('Tasa de Falsos Positivos (1 - Especificidad)')
plt.ylabel('Tasa de Verdaderos Positivos (Sensibilidad)')
plt.title('Curvas ROC — Comparativa de los 10 Modelos')
plt.legend(loc='lower right', fontsize=8)
plt.grid(True, alpha=0.3)
plt.show()

# ── 4.4 Tabla resumen con todas las métricas ─────────────────────────────
print('\n' + '='*115)
print(f'{"Modelo":<7}|{"Norm":<6}|{"Accuracy":<10}|{"Precision":<11}|'
      f'{"Recall":<9}|{"F1":<8}|{"Especif.":<10}|{"AUC":<8}|'
      f'{"Épocas":<8}|{"Mejor Val Loss"}')
print('='*115)

for nombre, datos in resultados.items():
    m   = datos['metricas']
    cfg = datos['config']
    n   = 'Sí' if cfg['norm'] else 'No'
    print(f'  {nombre:<5}| {n:<5}| {m["acc"]:<9.4f}| {m["prec"]:<10.4f}| '
          f'{m["rec"]:<8.4f}| {m["f1"]:<7.4f}| {m["esp"]:<9.4f}| '
          f'{m["auc"]:<7.4f}| {datos["epocas"]:<7}| {datos["mejor_val"]:.4f}')

print('='*115)

"""BLOQUE 4B"""

# ── Comparativa: Sin L2 vs Con L2 ─────────────────────────────────────────

# -- Curvas de convergencia comparadas (val loss) --
fig, axes = plt.subplots(5, 2, figsize=(14, 22))
axes = axes.flatten()

for i, nombre in enumerate(configuraciones.keys()):
    ax = axes[i]
    ax.plot(resultados[nombre]['hist_val'],    label='Sin L2',
            color='steelblue', linewidth=1.5)
    ax.plot(resultados_l2[nombre]['hist_val'], label=f'Con L2={L2_VALOR}',
            color='tomato', linewidth=1.5, linestyle='--')
    ax.set_title(f'Modelo {nombre} — Convergencia Val Loss')
    ax.set_xlabel('Épocas')
    ax.set_ylabel('Pérdida (BCE)')
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.suptitle('Impacto de la Regularización L2 en la Convergencia', fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

# -- Tabla comparativa de métricas --
print('\n' + '='*100)
print(f'{"Modelo":<8} | {"L2":<8} | {"Accuracy":<10} | {"Precision":<10} | '
      f'{"Recall":<8} | {"F1":<8} | {"Especif.":<10} | {"AUC"}')
print('='*100)

for nombre in configuraciones.keys():
    for etiqueta, res in [('Sin L2', resultados), (f'L2={L2_VALOR}', resultados_l2)]:
        m = res[nombre]['metricas']
        print(f'  {nombre:<6} | {etiqueta:<8} | {m["acc"]:<10.4f} | {m["prec"]:<10.4f} | '
              f'{m["rec"]:<8.4f} | {m["f1"]:<8.4f} | {m["esp"]:<10.4f} | {m["auc"]:.4f}')
    print('-'*100)

# -- Gráfica de barras: F1 con y sin L2 por modelo --
nombres   = list(configuraciones.keys())
f1_sin    = [resultados[n]['metricas']['f1']    for n in nombres]
f1_con    = [resultados_l2[n]['metricas']['f1'] for n in nombres]
auc_sin   = [resultados[n]['metricas']['auc']    for n in nombres]
auc_con   = [resultados_l2[n]['metricas']['auc'] for n in nombres]

x     = np.arange(len(nombres))
ancho = 0.35

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# F1
axes[0].bar(x - ancho/2, f1_sin, ancho, label='Sin L2',      color='steelblue', alpha=0.85)
axes[0].bar(x + ancho/2, f1_con, ancho, label=f'L2={L2_VALOR}', color='tomato', alpha=0.85)
axes[0].set_xticks(x)
axes[0].set_xticklabels(nombres)
axes[0].set_ylim(0, 1.05)
axes[0].set_ylabel('F1-Score')
axes[0].set_title('F1-Score: Sin L2 vs Con L2')
axes[0].legend()
axes[0].grid(True, alpha=0.3, axis='y')

# AUC
axes[1].bar(x - ancho/2, auc_sin, ancho, label='Sin L2',      color='steelblue', alpha=0.85)
axes[1].bar(x + ancho/2, auc_con, ancho, label=f'L2={L2_VALOR}', color='tomato', alpha=0.85)
axes[1].set_xticks(x)
axes[1].set_xticklabels(nombres)
axes[1].set_ylim(0, 1.05)
axes[1].set_ylabel('AUC-ROC')
axes[1].set_title('AUC: Sin L2 vs Con L2')
axes[1].legend()
axes[1].grid(True, alpha=0.3, axis='y')

plt.suptitle('Impacto de la Regularización L2 por Modelo', fontsize=13)
plt.tight_layout()
plt.show()

# -- Conclusión automática --
mejor_mejora_f1 = max(nombres,
    key=lambda n: resultados_l2[n]['metricas']['f1'] - resultados[n]['metricas']['f1'])
diff = (resultados_l2[mejor_mejora_f1]['metricas']['f1']
        - resultados[mejor_mejora_f1]['metricas']['f1'])
print(f'\nModelo donde L2 ayudó más (F1): Modelo {mejor_mejora_f1} '
      f'(mejora de {diff:+.4f} en F1)')

"""## Bloque 5 — Análisis Comparativo y Selección del Mejor Modelo"""

# ── 5.1 Comparativa Normalización vs Sin Normalización ───────────────────
# Comparamos pares equivalentes: A↔E, B↔F, C↔G, D↔H
pares = [('A', 'E'), ('B', 'F'), ('C', 'G'), ('D', 'H')]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for i, (sin_n, con_n) in enumerate(pares):
    ax = axes[i]
    ax.plot(resultados[sin_n]['hist_val'], label=f'Modelo {sin_n} (Sin Norm)',
            color='tomato', linestyle='--', linewidth=1.5)
    ax.plot(resultados[con_n]['hist_val'], label=f'Modelo {con_n} (Con Norm)',
            color='steelblue', linewidth=1.5)
    ax.set_title(f'Convergencia de Validación: {sin_n} vs {con_n}\n'
                 f'Neuronas: {resultados[sin_n]["config"]["neuronas"]} | '
                 f'LR: {resultados[sin_n]["config"]["lr"]}')
    ax.set_xlabel('Épocas')
    ax.set_ylabel('Pérdida Validación (BCE)')
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.suptitle('Impacto de la Normalización en la Convergencia', fontsize=14)
plt.tight_layout()
plt.show()

# Tabla comparativa norm vs sin norm
print('\n--- COMPARATIVA NORMALIZADOS VS SIN NORMALIZAR ---')
print(f'{"Modelo":<8}|{"Norm":<6}|{"Accuracy":<10}|{"Precision":<11}|{"Recall":<9}|{"F1":<8}|{"AUC"}')
print('-'*65)
for nombre in list(configuraciones.keys()):
    m   = resultados[nombre]['metricas']
    n   = 'Sí' if resultados[nombre]['config']['norm'] else 'No'
    print(f'  {nombre:<6}| {n:<5}| {m["acc"]:<9.4f}| {m["prec"]:<10.4f}| '
          f'{m["rec"]:<8.4f}| {m["f1"]:<7.4f}| {m["auc"]:.4f}')
print('-'*65)

# ── 5.2 Gráfica de barras comparativa (todas las métricas por modelo) ────
nombres      = list(resultados.keys())
met_keys     = ['acc', 'prec', 'rec', 'f1', 'esp', 'auc']
met_etiquetas = ['Accuracy', 'Precision', 'Recall', 'F1', 'Especificidad', 'AUC']

x     = np.arange(len(nombres))
ancho = 0.12

fig, ax = plt.subplots(figsize=(16, 6))
for j, (key, label) in enumerate(zip(met_keys, met_etiquetas)):
    valores = [resultados[n]['metricas'][key] for n in nombres]
    ax.bar(x + j * ancho, valores, ancho, label=label, alpha=0.85)

ax.set_xticks(x + ancho * 2.5)
ax.set_xticklabels(nombres, fontsize=11)
ax.set_ylim(0, 1.1)
ax.set_ylabel('Valor de Métrica')
ax.set_title('Comparativa de Todas las Métricas por Modelo')
ax.legend(loc='upper right', fontsize=9)
ax.axhline(y=0.8, color='gray', linestyle='--', alpha=0.4, label='Referencia 0.8')
ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

# ── 5.3 Selección del mejor modelo ───────────────────────────────────────
mejor_recall = max(resultados, key=lambda n: resultados[n]['metricas']['rec'])
mejor_auc    = max(resultados, key=lambda n: resultados[n]['metricas']['auc'])
mejor_f1     = max(resultados, key=lambda n: resultados[n]['metricas']['f1'])
mejor_acc    = max(resultados, key=lambda n: resultados[n]['metricas']['acc'])

print('\n' + '='*60)
print('RESULTADOS FINALES — MEJOR MODELO POR MÉTRICA')
print('='*60)
print(f'Mejor Accuracy:  Modelo {mejor_acc:<3} → {resultados[mejor_acc]["metricas"]["acc"]:.4f}')
print(f'Mejor Recall:    Modelo {mejor_recall:<3} → {resultados[mejor_recall]["metricas"]["rec"]:.4f}')
print(f'Mejor AUC:       Modelo {mejor_auc:<3} → {resultados[mejor_auc]["metricas"]["auc"]:.4f}')
print(f'Mejor F1:        Modelo {mejor_f1:<3} → {resultados[mejor_f1]["metricas"]["f1"]:.4f}')

print("""
── ANÁLISIS PROFUNDO (respuestas para el reporte) ──────────────────────────

1. NORMALIZACIÓN:
   Los modelos con normalización (E-J) convergen más rápido y con mayor
   estabilidad que sus equivalentes sin normalizar (A-D). Esto ocurre porque
   las características del dataset tienen escalas muy distintas (ej. Glucosa
   vs Edad), y sin normalizar el gradiente puede explotar o estancarse.

2. TRADE-OFF SENSIBILIDAD vs ESPECIFICIDAD:
   En un contexto clínico, es más costoso NO detectar a un diabético (FN)
   que dar una falsa alarma (FP). Por eso, el Recall (Sensibilidad) es la
   métrica prioritaria. El mejor modelo para uso clínico sería el de mayor
   Recall, aunque tenga menos Especificidad.

3. SOBREAJUSTE:
   Se controló con Early Stopping (paciencia=20) y regularización L2
   (weight_decay). Si la curva de validación sube mientras la de
   entrenamiento baja, hay sobreajuste.

4. DESBALANCE DE CLASES:
   El dataset tiene más no-diabéticos que diabéticos. Esto puede hacer que
   el Accuracy parezca alto aunque el modelo falle en detectar diabéticos.
   Por eso F1 y Recall son métricas más confiables en este problema.
""")

"""Bloque 6 — Batch sizes + K-Fold"""

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, roc_auc_score
import torch.nn as nn

# ── 6.1 Comparativa de Batch Sizes ───────────────────────────────────────
# Tomamos el mejor modelo por AUC para esta prueba
mejor_nombre = max(resultados, key=lambda n: resultados[n]['metricas']['auc'])
config_mejor = configuraciones[mejor_nombre]
print(f'Comparando batch sizes con el Modelo {mejor_nombre}...\n')

batch_sizes   = [4, 8, 16, 32, 64]
hist_batches  = {}

for bs in batch_sizes:
    print(f'  Batch size = {bs}...')
    if config_mejor['norm']:
        tl, vl = crear_loaders(X_train_norm_t, y_train_t,
                               X_val_norm_t,   y_val_t, batch_size=bs)
    else:
        tl, vl = crear_loaders(X_train_raw_t, y_train_t,
                               X_val_raw_t,   y_val_t, batch_size=bs)

    _, h_train, h_val, _, _ = entrenar_modelo(
        config=config_mejor, train_loader=tl, val_loader=vl,
        num_features=NUM_FEATURES, epocas=500, paciencia=20
    )
    hist_batches[bs] = {'train': h_train, 'val': h_val}

# Gráfica comparativa
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
colores = ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00']

for (bs, hist), color in zip(hist_batches.items(), colores):
    axes[0].plot(hist['train'], label=f'BS={bs}', color=color, linewidth=1.5)
    axes[1].plot(hist['val'],   label=f'BS={bs}', color=color, linewidth=1.5)

for ax, titulo in zip(axes, ['Pérdida Entrenamiento', 'Pérdida Validación']):
    ax.set_title(f'{titulo} — Modelo {mejor_nombre}')
    ax.set_xlabel('Épocas')
    ax.set_ylabel('Pérdida (BCE)')
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.suptitle('Impacto del Batch Size en la Convergencia', fontsize=13)
plt.tight_layout()
plt.show()


# ── 6.2 K-Fold Cross Validation (Bonus) ──────────────────────────────────
print(f'\nK-Fold (5 folds) sobre el Modelo {mejor_nombre}...\n')

X_full = np.vstack([X_train_norm, X_val_norm, X_test_norm])
y_full = np.concatenate([y_train, y_val, y_test])

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

metricas_folds = {'acc': [], 'prec': [], 'rec': [], 'f1': [], 'esp': [], 'auc': []}

for fold, (idx_train, idx_val) in enumerate(kf.split(X_full, y_full)):
    # Datos del fold
    Xf_train = torch.tensor(X_full[idx_train], dtype=torch.float32)
    yf_train = torch.tensor(y_full[idx_train], dtype=torch.float32).view(-1, 1)
    Xf_val   = torch.tensor(X_full[idx_val],   dtype=torch.float32)
    yf_val   = torch.tensor(y_full[idx_val],   dtype=torch.float32).view(-1, 1)

    tl, vl = crear_loaders(Xf_train, yf_train, Xf_val, yf_val, batch_size=32)

    modelo_f, _, _, _, _ = entrenar_modelo(
        config=config_mejor, train_loader=tl, val_loader=vl,
        num_features=NUM_FEATURES, epocas=500, paciencia=20
    )

    m = evaluar_modelo(modelo_f, Xf_val, yf_val)
    for key in metricas_folds:
        metricas_folds[key].append(m[key])

    print(f'  Fold {fold+1} | Acc={m["acc"]:.4f} | F1={m["f1"]:.4f} | AUC={m["auc"]:.4f}')

# Resultados con intervalos de confianza
print(f'\n{"─"*55}')
print(f'{"MÉTRICA":<14} {"MEDIA":>8} {"STD":>8} {"IC 95%":>18}')
print(f'{"─"*55}')

for key, vals in metricas_folds.items():
    media = np.mean(vals)
    std   = np.std(vals)
    ic_lo = media - 1.96 * std / np.sqrt(5)
    ic_hi = media + 1.96 * std / np.sqrt(5)
    print(f'{key.upper():<14} {media:>8.4f} {std:>8.4f}   [{ic_lo:.4f} – {ic_hi:.4f}]')

print(f'{"─"*55}')

# Gráfica de resultados por fold
fig, ax = plt.subplots(figsize=(10, 5))
x_folds = np.arange(1, 6)
for key in ['acc', 'f1', 'auc']:
    ax.plot(x_folds, metricas_folds[key], marker='o', label=key.upper(), linewidth=1.8)
    ax.axhline(np.mean(metricas_folds[key]), linestyle='--', alpha=0.5)

ax.set_xticks(x_folds)
ax.set_xticklabels([f'Fold {i}' for i in x_folds])
ax.set_ylim(0, 1.05)
ax.set_ylabel('Valor de Métrica')
ax.set_title(f'K-Fold (5 folds) — Modelo {mejor_nombre}\n'
             f'F1 media={np.mean(metricas_folds["f1"]):.4f} | '
             f'AUC media={np.mean(metricas_folds["auc"]):.4f}')
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()